### PR TITLE
Use `std::thread::available_parallelism` in place of num_cpus

### PR DESCRIPTION
**Pull request by joshtriplett**

### CODE REVIEW

**Comment by xacrimon** [comment]
Hi, thanks for the PR. Do you mind taking a look at fixing the lint issues and we can get this merged?

**Comment by joshtriplett** [comment]
As far as I can tell, all the lint issues are pre-existing issues in the code, unrelated to this change; I can send a separate PR for them, if that helps.

**Comment by joshtriplett** [comment]
@xacrimon https://github.com/xacrimon/dashmap/pull/200

**Comment by xacrimon** [comment]
Ah thanks, after taking a look. It looks like they popped up due to the toolchain change.

**Comment by xacrimon** [comment]
@joshtriplett Can you rebase onto master so that we can pass checks? Thank you!

**Comment by joshtriplett** [comment]
@xacrimon Done.

**Pull request merged**
