### PR TITLE
Swap over to use `SharedValue` and remove `util::to_mut`

### LINKED ISSUE #10: Undefined Behavior in `util::to_mut`
You can never transmute a `&T` to a `&mut T` in *any* way. This is instant undefined behavior.

Currently there is no fast way to get a `(&K, &mut V)` from the standard hashmap, so your out of luck it seems, but there is a way to fix this! Instead of storing `HashMap<K, V>`, store `HashMap<K, UnsafeCell<V>>`. This way you can soundly get a `&mut V` from `get_key_value` (so long as you are also holding a write shard).

### PR DESCRIPTION
**Pull request by KrishnaSannasi**
Fixes #10

### CODE REVIEW

**Comment by xacrimon** [comment]
I want to expose shards and determine_map though. That is intentional.

**Comment by KrishnaSannasi** [comment]
@xacrimon Sorry took those out by accident in last commit

**Comment by KrishnaSannasi** [comment]
I don't think that keeping `shards` in the public api is a good idea, it fixes the representation of the shards and makes changes like this one a breaking change.

**Comment by xacrimon** [comment]
Right. Maybe explicitly say it's unstable and can change at any point? Yeah I like that idea.

**Comment by KrishnaSannasi** [comment]
@xacrimon Yeah, that could work, maybe put it behind the nightly flag?

**Comment by KrishnaSannasi** [comment]
That could be another PR, this one is good to go

**Comment by xacrimon** [comment]
Alright. Merging

**Pull request merged**
