### PR TITLE
update ahash and hashbrown version

### PR DESCRIPTION
**Pull request by zh-jq**
update dependency version

### CODE REVIEW

**Comment by repi** [comment]
Would be great to be able to get this in

**Comment by xacrimon** [comment]
Sadly we can't update ahash due to the fact that it is exposed in public API.

**Comment by davidpdrsn** [comment]
@xacrimon Any chance you would consider releasing a new major that includes this? Might also be cool to remove "ahash" from the exposed API to prevent such issues in the future. Not sure if thats possible.

Its leading to duplicate dependencies for me.

**Comment by xacrimon** [comment]
V4 "The Maintenance Release" will be inbound shortly taking care of this. Thanks.

**Pull request closed without merging**
