### PR TITLE
chore: bump hashbrown to v0.13 && bump MSRV

### PR DESCRIPTION
**Pull request by TennyZhuang**
Signed-off-by: TennyZhuang <zty0826@gmail.com>

### CODE REVIEW

**Comment by xacrimon** [comment]
This PR increases the MSRV beyond what I'd like to do right now. Is that a requirement of the `hashbrown` bump?

**Comment by TennyZhuang** [comment]
@xacrimon Yes, hashbrown also bumped their MSRV to Rust 1.61, I guess it's acceptable while the stable version has been bumped to 1.66.

**Comment by TennyZhuang** [comment]
Ref: https://github.com/rust-lang/hashbrown/blob/7d01f51be911c656d3b6aa49624ddcc4644e1629/Cargo.toml#L13

**Comment by Razican** [comment]
Hello, Rust 1.68 is now stable, and Rust 1.61 has been out since May 2022. Would it be possible to merge this and release it? We're getting duplicate hashbrown dependency versions due to dashmap in Boa :( it would be nice to get a consistent versioning across the crate.

**Comment by cuviper** [comment]
FWIW, hashbrown 0.14 is out now, although that further requires Rust 1.64.

**Comment by TennyZhuang** [comment]
I'd like to bump it to 0.14 in another PR, but I guess the PR can be merged first.

**Pull request closed without merging**
