### PR TITLE
add remove_with_cond method

### PR DESCRIPTION
**Pull request by Future2100**
remove the entry only when the cond matches.

### CODE REVIEW

**Comment by xacrimon** [comment]
Thanks, I'll be taking a look at this soon.

**Comment by xacrimon** [comment]
Due to time constraints I will have to delay a little.

**Comment by xacrimon** [comment]
Scheduled for review this Friday.

**Comment by xacrimon** [comment]
Added in the latest release.

**Comment by Future2100** [comment]
thx

**Comment by Future2100** [comment]
You added the inner interface but lost the outer interface.

**Comment by xacrimon** [comment]
Ah, my mistake. Just published a patch to fix this.

**Comment by Future2100** [comment]
Ok, thx. I want to use it so please ASAP.

**Comment by xacrimon** [comment]
It's already out.

**Comment by Future2100** [comment]
Nice, thx guy.

**Pull request closed without merging**
