### PR TITLE
Implement ReadOnlyView

### PR DESCRIPTION
**Pull request by w1th0utnam3**
This is an implementation of what was discussed in issue https://github.com/xacrimon/dashmap/issues/65.

Feel free to request naming/API changes or more tests/comments.

### CODE REVIEW

**Comment by w1th0utnam3** [comment]
Whoops, there is an unnecessary `use std::fs::read;` in there. Probably because of my IDE.

**Comment by w1th0utnam3** [comment]
Open points:
- Maybe use a different name than `ReadOnlyView`? Maybe `ReadDashMap`\`ReadOnlyDashMap`?
- Maybe the `get` method of the `DashMap` should be modified to more closely match the behavior of the standard `HashMap`? An additional `get_key_value()` could be used for the current behavior. At least for me the current behavior was a little bit surprising. For the `ReadOnlyView` I used the same API as the standard `HashMap` because this allows to more easily replace the usage of `HashMap` with `DashMap`.

**Comment by xacrimon** [comment]
Sorry for the delay. I will be taking some time for this PR on Friday.

**Comment by xacrimon** [comment]
Apologies for the delay. I will review when I have time.

**Comment by w1th0utnam3** [comment]
@xacrimon Cool to see that you merged it. Did you consider the points i mentioned above (https://github.com/xacrimon/dashmap/pull/66#issuecomment-599642418)?

**Comment by xacrimon** [comment]
I did consider them. I don't have a ton of time and I considered the current state good for merging and release.

**Pull request merged**
