### PR TITLE
Implement try_entry_res function for DashMap

### PR DESCRIPTION
**Pull request by DrSloth**
Implements the `try_entry_res` function as an additional function.

### CODE REVIEW

**Comment by notgull** [comment]
I'm not a huge fan of the name. How about `entry_or_else` or something else to that effect?

**Comment by DrSloth** [comment]
I guess `entry_or_else` would kind of imply the function receiving a function. How about `entry_or_err`?

**Comment by xacrimon** [comment]
IMO this strays too far into the territory of specialized functions. Consider matching instead.

**Comment by DrSloth** [comment]
The idea behind this wasn't making `?` possible, but enabling the user to retrieve back the owned key value when inserting fails which is currently not possible as it seems.

**Pull request closed without merging**
